### ISSUE TITLE
Tracking HTTP+JSON thrift compatibility work

### ISSUE THREAD

**Issue by Raynos** [uber/zanzibar#68]
## Thrift semantics TODO:

 - [ ] Logger.Warn() about unexpected fields in JSON payload
 - [ ] Required field semantics
 - [ ] Recursive converter functions
 - [ ] Do not parse JSON body on GET / DELETE method
 - [ ] Check Content-Type header before parsing
 - [ ] Add support for parsing params to server
 - [ ] Add support for "-" for non-body fields
 - [ ] Add support for exceptions with the same status code
 - [ ] Remove req.def = boxed annotation
 - [ ] Ensure status, method & path are mandatory annotations
 - [ ] Add support for http.ref = headers
 - [ ] Add support for http.ref = query
 - [ ] Add support for http.ref = body
 - [ ] Add support for headerGroups
 - [ ] Remove zanzibar.meta annotation
 - [ ] Remove zanzibar.handler annotation

### Logger.Warn() about unexpected fields in JSON payload

Modify easyjson to track keys in objects that are skipped.

### Required field semantics

Add support for marking a field required. Need to change thriftrw
to generate the required tag. Verify that it works as expected.

### Recursive converter functions

Currently our server / client struct conversions are not
recursive and only convert a subset of the fields. 
These functions need to be generated in a recursive fashion.

### Do not parse JSON body on GET / DELETE method

Do not parse the body.

### Check Content-Type header before parsing

Currently we naively parse json, need to verify content-type
header before attempting to parse.

### Add support for parsing params to server

Currently on the client supports params, need to add support
to the server for this.

### Add support for "-" for non-body fields

Some fields come from other parts of the HTTP request, aka
headers, params, query, etc.

Need to ensure generated code has "-" annotation to not parse
said field from the body.

This will require a thriftrw change, potentially. Will probably
need to add an annotation conversion logic to customize the
semantics of our annotations and how thriftrw parse them.

### Add support for exceptions with the same status code

Currently HTTP clients do not support exceptions with duplicate
status codes.

### Remove req.def = boxed annotation

This annotation is deprecated and should not be used, instead
we should use many top level optional & required fields.

### Ensure status, method & path are mandatory annotations

Verify our code generation error messages when these are missing.

### Add support for http.ref = headers

We need to be able to read header keys into body fields
This needs to happen for both client & server.

### Add support for http.ref = query

We need to be able to read/write fields from query parameters
in both the client and the server.

### Add support for http.ref = body

We need to be able to change the JSON body name that this field
is written or read from. This is generally for camelCase vs
snake case.

### Add support for headerGroups

When validating required headers some clients have many, many
required headers ( more then 10 ). To keep the code clean and DRY
we want to be able to define a struct with a set of required
headers and annotate a thrift method with "headerGroups=structName".

This would mean that this thrift method has a set of required
headers defined in the zanzibar.http.headers annotation as well
as the zanzibar.headerGroups annotation.

### Remove zanzibar.meta annotation

This is a dead annotation with no meaning

### Remove zanzibar.handler annotation

This is a dead annotation with no meaning
